<a href="https://colab.research.google.com/github/emmelinetsen/deep_learning/blob/master/dl-w-pytorch/Chapter4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

In [2]:
t_c

tensor([ 0.5000, 14.0000, 15.0000, 28.0000, 11.0000,  8.0000,  3.0000, -4.0000,
         6.0000, 13.0000, 21.0000])

In [3]:
t_u

tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
        48.4000, 60.4000, 68.4000])

In [0]:
def model(t_u, w, b):
 return w * t_u + b

In [0]:
def loss_fn(t_p, t_c):
 squared_diffs = (t_p - t_c)**2
 return squared_diffs.mean()

In [6]:
w = torch.ones(1)
b = torch.zeros(1)
t_p = model(t_u, w, b)
t_p

tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
        48.4000, 60.4000, 68.4000])

In [7]:
loss = loss_fn(t_p, t_c)
loss

tensor(1763.8846)

In [0]:
delta = 0.1
loss_rate_of_change_w = \
 (loss_fn(model(t_u, w + delta, b), t_c) -
 loss_fn(model(t_u, w - delta, b), t_c)) / (2.0 * delta)

In [10]:
learning_rate = 1e-2
w = w - learning_rate * loss_rate_of_change_w
w

tensor([-89.3460])

In [11]:
loss_rate_of_change_b = \
 (loss_fn(model(t_u, w, b + delta), t_c) -
 loss_fn(model(t_u, w, b - delta), t_c)) / (2.0 * delta)
b = b - learning_rate * loss_rate_of_change_b
b

tensor([92.9000])

In [0]:
def loss_fn(t_p, t_c):
 squared_diffs = (t_p - t_c)**2
 return squared_diffs.mean()

def dloss_fn(t_p, t_c):
 dsq_diffs = 2 * (t_p - t_c)
 return dsq_diffs

def model(t_u, w, b):
 return w * t_u + b

def dmodel_dw(t_u, w, b):
 return t_u

def dmodel_db(t_u, w, b):
 return 1.0

def grad_fn(t_u, t_c, t_p, w, b):
 dloss_dw = dloss_fn(t_p, t_c) * dmodel_dw(t_u, w, b)
 dloss_db = dloss_fn(t_p, t_c) * dmodel_db(t_u, w, b)
 return torch.stack([dloss_dw.mean(), dloss_db.mean()])

def training_loop(n_epochs, learning_rate, params, t_u, t_c):
 for epoch in range(1, n_epochs + 1):
  w, b = params
  t_p = model(t_u, w, b)
  loss = loss_fn(t_p, t_c)
  grad = grad_fn(t_u, t_c, t_p, w, b)
  params = params - learning_rate * grad
  print('Epoch %d, Loss %f' % (epoch, float(loss)))
 return params


In [20]:
training_loop(
 n_epochs = 100,
 learning_rate = 1e-2,
 params = torch.tensor([1.0, 0.0]),
 t_u = t_u,
 t_c = t_c)

Epoch 1, Loss 1763.884644
Epoch 2, Loss 5802484.500000
Epoch 3, Loss 19408031744.000000
Epoch 4, Loss 64915909902336.000000
Epoch 5, Loss 217130439561707520.000000
Epoch 6, Loss 726257020202974707712.000000
Epoch 7, Loss 2429181687085405986357248.000000
Epoch 8, Loss 8125117236949438203699396608.000000
Epoch 9, Loss 27176865195881116022129584766976.000000
Epoch 10, Loss 90901075478458130961171361977860096.000000
Epoch 11, Loss inf
Epoch 12, Loss inf
Epoch 13, Loss inf
Epoch 14, Loss inf
Epoch 15, Loss inf
Epoch 16, Loss inf
Epoch 17, Loss inf
Epoch 18, Loss inf
Epoch 19, Loss inf
Epoch 20, Loss inf
Epoch 21, Loss inf
Epoch 22, Loss inf
Epoch 23, Loss nan
Epoch 24, Loss nan
Epoch 25, Loss nan
Epoch 26, Loss nan
Epoch 27, Loss nan
Epoch 28, Loss nan
Epoch 29, Loss nan
Epoch 30, Loss nan
Epoch 31, Loss nan
Epoch 32, Loss nan
Epoch 33, Loss nan
Epoch 34, Loss nan
Epoch 35, Loss nan
Epoch 36, Loss nan
Epoch 37, Loss nan
Epoch 38, Loss nan
Epoch 39, Loss nan
Epoch 40, Loss nan
Epoch 41, Loss

tensor([nan, nan])